### ISSUE TITLE
Add notification for window user (when `load_module modules/ngx_http_js_module.so`)

### ISSUE THREAD

**Issue by ccppoo** [jirutka/njs-typescript-starter#5]
I do really appreciate for your repos and nginx binary builds for simple tests.

It will be more better for starters like me, new to nginx to add warnings about windows limitation on nginx.

you know NJS has most of their functionality by using `load_module modules/ngx_http_js_module.so;`

but testing in windows breaks like  you mentioned in `nginx-binaries` repo.

https://github.com/jirutka/nginx-binaries#_footnoteref_5

so what about adding scripts for those who don't read docs top to bottom like me?

```js
// warnWindow.mjs

import { platform } from "os";
import { readFileSync } from "fs";
import path from "path";

const __dirname = path.resolve();
const nginxConfig = `${__dirname}/nginx.conf`;

function hasWindowsLimitation() {
  if (platform() == "win32") {
    if (
      readFileSync(nginxConfig, "utf-8").includes(
        "load_module modules/ngx_http_js_module.so;"
      )
    ) {
      console.log("windows are not allowed to use this");
    }
  }
  return false;
}
```

could be useful for starters?

I almost got to compile njs and nginx for myself

Thanks!

**Comment by jirutka** [comment]
This is a documentation issue. I’ve updated the Prerequisites section to clarify this. Thank you for noticing!

> load_module modules/ngx_http_js_module.so;

This is not used anywhere in this project. The integration tests by default use nginx from nginx-binaries which has `ngx_http_js_module` statically linked into the nginx binary, so `load_module …` is not just unnecessary, it doesn’t work. The problem is that njs just doesn’t support Windows, so you cannot run nginx with njs directly on Windows.
